openapi: 3.0.3
info:
  title: OdengFinance Accounts API
  description: API for managing financial accounts in the OdengFinance ledger system
  version: 1.0.0
  contact:
    name: OdengFinance Team
    email: support@odengfinance.com

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://api.odengfinance.com/v1
    description: Production server

tags:
  - name: Account
    description: Operations related to financial accounts

paths:
  /api/v1/accounts:
    post:
      tags:
        - Account
      summary: Create a new account
      description: Creates a new financial account in the ledger system
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreateAccountRequest:
      type: object
      required:
        - name
        - accountType
      properties:
        name:
          type: string
          description: The name of the account
          minLength: 1
          maxLength: 255
          example: "Savings Account"
        accountType:
          $ref: '#/components/schemas/AccountType'

    AccountResponse:
      type: object
      required:
        - id
        - userGroupId
        - name
        - accountType
        - accountStatus
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier of the account
          example: 12345
        userGroupId:
          type: integer
          format: int64
          description: The ID of the user group that owns this account
          example: 1
        name:
          type: string
          description: The name of the account
          example: "Savings Account"
        accountType:
          $ref: '#/components/schemas/AccountType'
        accountStatus:
          $ref: '#/components/schemas/AccountStatus'

    AccountType:
      type: string
      description: The type of account following accounting principles
      enum:
        - ASSET
        - LIABILITY
        - EQUITY
        - INCOME
        - EXPENSE
      example: ASSET

    AccountStatus:
      type: string
      description: The current status of the account
      enum:
        - ACTIVE
        - INACTIVE
      example: ACTIVE

    ErrorResponse:
      $ref: './common-components.yml#/components/schemas/ErrorResponse'

