openapi: 3.0.3
info:
  title: OdengFinance Accounts API
  description: API for managing financial accounts in the OdengFinance ledger system
  version: 1.0.0
  contact:
    name: OdengFinance Team
    email: support@odengfinance.com

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://api.odengfinance.com/v1
    description: Production server

tags:
  - name: Account
    description: Operations related to financial accounts

paths:
  /api/v1/accounts:
    get:
      tags:
        - Account
      summary: Get accounts by user ID
      description: |
        Retrieves all accounts associated with a specific user.
        Requires permission to access the specified user's data.
      operationId: getAccounts
      parameters:
        - name: userId
          in: query
          required: true
          description: The unique identifier of the user whose accounts to retrieve
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Accounts retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountListResponse'
        '400':
          $ref: './common-components.yml#/components/responses/BadRequest'
        '403':
          $ref: './common-components.yml#/components/responses/Forbidden'
        '404':
          $ref: './common-components.yml#/components/responses/NotFound'
        '500':
          $ref: './common-components.yml#/components/responses/InternalServerError'

    post:
      tags:
        - Account
      summary: Create a new account
      description: Creates a new financial account in the ledger system
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/accounts/{accountId}/share:
    post:
      tags:
        - Account
      summary: Share an account with a user
      description: |
        Shares an account with a specific user, granting them access to view
        and manage the account. Only the account owner can share the account.
        If the user already has access to the account, an error will be returned.
      operationId: shareAccount
      parameters:
        - name: accountId
          in: path
          required: true
          description: The unique identifier of the account to share
          schema:
            type: integer
            format: int64
            example: 12345
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShareAccountRequest'
      responses:
        '204':
          description: Account shared successfully
        '400':
          $ref: './common-components.yml#/components/responses/BadRequest'
        '403':
          $ref: './common-components.yml#/components/responses/Forbidden'
        '404':
          $ref: './common-components.yml#/components/responses/NotFound'
        '409':
          description: Conflict - Account is already shared with this user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: './common-components.yml#/components/responses/InternalServerError'

components:
  schemas:
    CreateAccountRequest:
      type: object
      required:
        - name
        - accountType
      properties:
        name:
          type: string
          description: The name of the account
          minLength: 1
          maxLength: 255
          example: "Savings Account"
        accountType:
          $ref: '#/components/schemas/AccountType'

    AccountResponse:
      type: object
      required:
        - id
        - name
        - accountType
        - accountStatus
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier of the account
          example: 12345
        name:
          type: string
          description: The name of the account
          example: "Savings Account"
        accountType:
          $ref: '#/components/schemas/AccountType'
        accountStatus:
          $ref: '#/components/schemas/AccountStatus'

    AccountListResponse:
      type: object
      required:
        - accounts
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/AccountResponse'
          example:
            - id: 1
              name: "Savings Account"
              accountType: "ASSET"
              accountStatus: "ACTIVE"
            - id: 2
              name: "Checking Account"
              accountType: "ASSET"
              accountStatus: "ACTIVE"
            - id: 3
              name: "Credit Card"
              accountType: "LIABILITY"
              accountStatus: "ACTIVE"

    ShareAccountRequest:
      type: object
      required:
        - userId
      properties:
        userId:
          type: integer
          format: int64
          description: The ID of the user to share the account with
          example: 101

    AccountType:
      type: string
      description: The type of account following accounting principles
      enum:
        - ASSET
        - LIABILITY
        - EQUITY
        - INCOME
        - EXPENSE
      example: ASSET

    AccountStatus:
      type: string
      description: The current status of the account
      enum:
        - ACTIVE
        - INACTIVE
      example: ACTIVE

    ErrorResponse:
      $ref: './common-components.yml#/components/schemas/ErrorResponse'

