openapi: 3.0.3
info:
  title: Common Components
  description: Shared components used across all OdengFinance APIs
  version: 1.0.0

components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - timestamp
        - status
        - error
        - messages
      properties:
        timestamp:
          type: string
          format: date-time
          description: The timestamp when the error occurred
          example: "2025-11-03T10:15:30Z"
        status:
          type: integer
          description: HTTP status code
          example: 400
        error:
          type: string
          description: Error type
          example: "Bad Request"
        messages:
          type: array
          description: List of error messages
          items:
            type: string
          example: ["Username is required", "Email format is invalid"]

    ValidationError:
      type: object
      required:
        - field
        - message
      properties:
        field:
          type: string
          description: The field that failed validation
          example: "email"
        message:
          type: string
          description: Validation error message
          example: "Email format is invalid"

    PaginationMetadata:
      type: object
      required:
        - page
        - pageSize
        - totalElements
        - totalPages
      properties:
        page:
          type: integer
          description: Current page number (0-indexed)
          example: 0
        pageSize:
          type: integer
          description: Number of items per page
          example: 20
        totalElements:
          type: integer
          format: int64
          description: Total number of elements
          example: 100
        totalPages:
          type: integer
          description: Total number of pages
          example: 5

  parameters:
    PageParam:
      name: page
      in: query
      description: Page number (0-indexed)
      required: false
      schema:
        type: integer
        default: 0
        minimum: 0

    PageSizeParam:
      name: pageSize
      in: query
      description: Number of items per page
      required: false
      schema:
        type: integer
        default: 20
        minimum: 1
        maximum: 100

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Unauthorized - Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Forbidden:
      description: Forbidden - Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

