openapi: 3.0.3
info:
  title: OdengFinance Journal Entries API
  description: API for managing journal entries in the OdengFinance ledger system
  version: 1.0.0
  contact:
    name: OdengFinance Team
    email: support@odengfinance.com

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://api.odengfinance.com/v1
    description: Production server

tags:
  - name: Journal Entries
    description: Operations related to journal entries and double-entry bookkeeping

paths:
  /journal-entries:
    post:
      tags:
        - Journal Entries
      summary: Create a new journal entry
      description: |
        Creates a new journal entry following double-entry accounting principles.
        The entry will have exactly two items: one CREDIT for the source account
        and one DEBIT for the destination account.
      operationId: createJournalEntry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJournalEntryRequest'
      responses:
        '201':
          description: Journal entry created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JournalEntryResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /journal-entries/{journalEntryId}:
    get:
      tags:
        - Journal Entries
      summary: Get journal entry by ID
      description: Retrieves a specific journal entry with all its entry items
      operationId: getJournalEntryById
      parameters:
        - name: journalEntryId
          in: path
          required: true
          description: The unique identifier of the journal entry
          schema:
            type: integer
            format: int64
            example: 12345
      responses:
        '200':
          description: Journal entry retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JournalEntryResponse'
        '404':
          description: Journal entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreateJournalEntryRequest:
      type: object
      required:
        - amount
        - description
        - memo
        - transactionDate
        - sourceAccountId
        - destinationAccountId
      properties:
        amount:
          $ref: '#/components/schemas/Money'
        description:
          type: string
          description: A brief description of the transaction
          minLength: 1
          maxLength: 500
          example: "Monthly Salary"
        memo:
          type: string
          description: Additional notes or details about the transaction
          maxLength: 1000
          example: "January 2025 salary deposit"
        transactionDate:
          type: string
          format: date-time
          description: The date and time when the transaction occurred
          example: "2025-11-03T10:15:30Z"
        sourceAccountId:
          type: integer
          format: int64
          description: The account to be CREDITED (source of funds)
          example: 100
        destinationAccountId:
          type: integer
          format: int64
          description: The account to be DEBITED (destination of funds)
          example: 200

    JournalEntryResponse:
      type: object
      required:
        - id
        - description
        - memo
        - transactionDate
        - entryItems
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier of the journal entry
          example: 12345
        description:
          type: string
          description: A brief description of the transaction
          example: "Monthly Salary"
        memo:
          type: string
          description: Additional notes or details about the transaction
          example: "January 2025 salary deposit"
        transactionDate:
          type: string
          format: date-time
          description: The date and time when the transaction occurred
          example: "2025-11-03T10:15:30Z"
        entryItems:
          type: array
          description: The list of entry items (debits and credits)
          items:
            $ref: '#/components/schemas/EntryItemResponse'
          minItems: 2
          maxItems: 2

    EntryItemResponse:
      type: object
      required:
        - id
        - accountId
        - journalId
        - billingAmount
        - currency
        - direction
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier of the entry item
          example: 67890
        accountId:
          type: integer
          format: int64
          description: The ID of the account this entry item affects
          example: 100
        journalId:
          type: integer
          format: int64
          description: The ID of the parent journal entry
          example: 12345
        billingAmount:
          type: number
          format: double
          description: The monetary amount of this entry item
          example: 5000.00
        currency:
          $ref: '#/components/schemas/Currency'
        direction:
          $ref: '#/components/schemas/Direction'

    Money:
      type: object
      required:
        - amount
        - currency
      properties:
        amount:
          type: number
          format: double
          description: The monetary amount
          minimum: 0.01
          example: 5000.00
        currency:
          $ref: '#/components/schemas/Currency'

    Currency:
      type: string
      description: ISO 4217 currency code
      enum:
        - USD
        - EUR
        - GBP
        - JPY
        - PHP
      example: USD

    Direction:
      type: string
      description: The direction of the entry (debit or credit)
      enum:
        - DEBIT
        - CREDIT
      example: DEBIT

    ErrorResponse:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
      properties:
        timestamp:
          type: string
          format: date-time
          description: The timestamp when the error occurred
          example: "2025-11-03T10:15:30Z"
        status:
          type: integer
          description: HTTP status code
          example: 400
        error:
          type: string
          description: Error type
          example: "Bad Request"
        message:
          type: string
          description: Detailed error message
          example: "Invalid account ID"
        path:
          type: string
          description: The API path that was called
          example: "/api/v1/journal-entries"

