openapi: 3.0.3
info:
  title: OdengFinance User API
  description: API for managing user related actions in the OdengFinance ledger system
  version: 1.0.0
  contact:
    name: OdengFinance Team
    email: support@odengfinance.com

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://api.odengfinance.com/v1
    description: Production server

tags:
  - name: User
    description: Operations related to user management

paths:
  /auth/v1/user:
    post:
      tags:
        - User
      summary: Create a new user
      description: Creates a new user account
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
        '400':
          $ref: './common-components.yml#/components/responses/BadRequest'
        '500':
          $ref: './common-components.yml#/components/responses/InternalServerError'

components:
  schemas:
    CreateUserRequest:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          description: The username for the new user
          minLength: 3
          maxLength: 50
          example: "johndoe"
        email:
          type: string
          format: email
          description: The email address of the user
          example: "john.doe@example.com"
        password:
          type: string
          format: password
          description: The password for the user account
          minLength: 8
          example: "SecureP@ssw0rd"
    CreateUserResponse:
      type: object
      required:
        - username
        - email
      properties:
        username:
          type: string
          description: The username
          example: "johndoe"
        email:
          type: string
          format: email
          description: The email address
          example: "john.doe@example.com"